[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "jamdict>=0.1a11.post2",
    "jamdict-data>=1.5",
    "pykakasi>=2.3.0",
    "requests>=2.32.5",
    "romkan>=0.2.1",
]
